export const latestProjectsPropsPrimary = [
    {
        id: 1.1,
        title: "power organizer",
        alt: "power-organizer",
        imgSrc: "../../images/power-organizer1.jpg",
        linkHref: "http://3.76.123.244/login",
        technologies: ["React.js", "JavaScript", "Material UI"],
        // description: "helps you keep track of your todos depending on the calendar",
        description: "helps you keep track of your todos, in your account",
        codeLinkHref: "https://github.com/AnaSeiculescu/to-do-list-react",
    },
    {
        id: 1.2,
        title: "dizzy notes",
        alt: "dizzy-notes",
        imgSrc: "../../images/dizzy-notes2.jpg",
        linkHref: "https://anaseiculescu.github.io/keep-notes/",
        technologies: ["JavaScript", "Masonry", "CSS", "Web Storage API"],
        description: "your can add and delete coloured notes, storaged with localStorage, or with JSON server",
        codeLinkHref: "https://github.com/AnaSeiculescu/keep-notes",
    },
    {
        id: 1.3,
        title: "call a cat with the CatAPI",
        alt: "call-a-cat",
        imgSrc: "../../images/catAPI.jpg",
        linkHref: "https://cat-caller.netlify.app/#",
        technologies: ["React.js", "The Cat API", "Bootstrap", "Netlify"],
        description: "call how many cat you want to colect, from The Cat API",
        codeLinkHref: "https://github.com/AnaSeiculescu/Call-a-Cat-API",
    },
    {
        id: 1.4,
        title: "collection map",
        alt: "collection-map",
        imgSrc: '"../../images/collection-map1.jpg',
        linkHref: "https://anaseiculescu.github.io/collection-map/",
        technologies: ["JavaScript", "jQuery", "GoogleMapsAPI", "CSS"],
        description: "search for locations and you can collect them on your map and in your list",
        codeLinkHref: "https://github.com/AnaSeiculescu/collection-map",
    },
];

export const latestProjectsPropsSecondary = [
    {
        id: 1.5,
        title: "power organizer",
        alt: "power-organizer",
        imgSrc: "../../images/power-organizer1.jpg",
        linkHref: "http://3.76.123.244/login",
        technologies: ["React.js", "JavaScript", "Material UI"],
        // description: "helps you keep track of your todos depending on the calendar",
        description: "helps you keep track of your todos, in your account",
        codeLinkHref: "https://github.com/AnaSeiculescu/to-do-list-react",
    },
    {
        id: 1.6,
        title: "dizzy notes",
        alt: "dizzy-notes",
        imgSrc: "../../images/dizzy-notes2.jpg",
        linkHref: "https://anaseiculescu.github.io/keep-notes/",
        technologies: ["JavaScript", "Masonry", "CSS", "Web Storage API"],
        description: "your can add and delete coloured notes, storaged with localStorage, or with JSON server",
        codeLinkHref: "https://github.com/AnaSeiculescu/keep-notes",
    },
    {
        id: 1.7,
        title: "call a cat with the CatAPI",
        alt: "call-a-cat",
        imgSrc: "../../images/catAPI.jpg",
        linkHref: "https://cat-caller.netlify.app/#",
        technologies: ["React.js", "The Cat API", "Bootstrap", "Netlify"],
        description: "call how many cat you want to colect, from The Cat API",
        codeLinkHref: "https://github.com/AnaSeiculescu/Call-a-Cat-API",
    },
    {
        id: 1.8,
        title: "collection map",
        alt: "collection-map",
        imgSrc: '"../../images/collection-map1.jpg',
        linkHref: "https://anaseiculescu.github.io/collection-map/",
        technologies: ["JavaScript", "jQuery", "GoogleMapsAPI", "CSS"],
        description: "search for locations and you can collect them on your map and in your list",
        codeLinkHref: "https://github.com/AnaSeiculescu/collection-map",
    },
];

export const oldestProjectsPropsPrimary = [
    {
        id: 2.1,
        title: "my previous portfolio",
        alt: "previous-portfolio",
        imgSrc: '"../../images/previous-portfolio.jpg',
        linkHref: "https://anaseiculescu.github.io/Portfolio/",
        technologies: ["JavaScript", "jQuery", "CSS"],
        description: "a development of my imagination through my beginner skills",
        codeLinkHref: "https://github.com/AnaSeiculescu/Portfolio",
    },
    {
        id: 2.2,
        title: "rock paper scissors lizard spock",
        alt: "rock-paper-scissors-lizard-spock",
        imgSrc: '"../../images/rock-paper-scissors-lizard-spock.jpg',
        linkHref: "https://anaseiculescu.github.io/rock-paper-scissors-lizard-spock/",
        technologies: ["JavaScript", "CSS", "HTML"],
        description: "try your luck! play the game!",
        codeLinkHref: "https://github.com/AnaSeiculescu/rock-paper-scissors-lizard-spock",
    },
    {
        id: 2.3,
        title: "breakfast recipes",
        alt: "breakfast-recipes",
        imgSrc: '"../../images/breakfast-recipes.jpg',
        linkHref: "https://anaseiculescu.github.io/breakfast-recipes/",
        technologies: ["CSS", "HTML", "Photoshop"],
        description: "a responsive site, with the cuttest responsive logo :)",
        codeLinkHref: "https://github.com/AnaSeiculescu/breakfast-recipes",
    },
    {
        id: 2.4,
        title: "color picker",
        alt: "color-picker",
        imgSrc: '"../../images/color-picker.jpg',
        linkHref: "https://anaseiculescu.github.io/ana_s_color_picker/",
        technologies: ["JavaScript", "CSS", "jQuery"],
        description: "select the hue you prefer to change the panel, you also can save a list of preferred colors",
        codeLinkHref: "https://github.com/AnaSeiculescu/ana_s_color_picker",
    },
];

export const oldestProjectsPropsSecondary = [
    {
        id: 2.8,
        title: "my previous portfolio",
        alt: "previous-portfolio",
        imgSrc: '"../../images/previous-portfolio.jpg',
        linkHref: "https://anaseiculescu.github.io/Portfolio/",
        technologies: ["JavaScript", "jQuery", "CSS"],
        description: "a development of my imagination through my beginner skills",
        codeLinkHref: "https://github.com/AnaSeiculescu/Portfolio",
    },
    {
        id: 2.7,
        title: "rock paper scissors lizard spock",
        alt: "rock-paper-scissors-lizard-spock",
        imgSrc: '"../../images/rock-paper-scissors-lizard-spock.jpg',
        linkHref: "https://anaseiculescu.github.io/rock-paper-scissors-lizard-spock/",
        technologies: ["JavaScript", "CSS", "HTML"],
        description: "try your luck! play the game!",
        codeLinkHref: "https://github.com/AnaSeiculescu/rock-paper-scissors-lizard-spock",
    },
    {
        id: 2.6,
        title: "breakfast recipes",
        alt: "breakfast-recipes",
        imgSrc: '"../../images/breakfast-recipes.jpg',
        linkHref: "https://anaseiculescu.github.io/breakfast-recipes/",
        technologies: ["CSS", "HTML", "Photoshop"],
        description: "a responsive site, with the cuttest responsive logo :)",
        codeLinkHref: "https://github.com/AnaSeiculescu/breakfast-recipes",
    },
    {
        id: 2.5,
        title: "color picker",
        alt: "color-picker",
        imgSrc: '"../../images/color-picker.jpg',
        linkHref: "https://anaseiculescu.github.io/ana_s_color_picker/",
        technologies: ["JavaScript", "CSS", "jQuery"],
        description: "select the hue you prefer to change the panel, you also can save a list of preferred colors",
        codeLinkHref: "https://github.com/AnaSeiculescu/ana_s_color_picker",
    },
];
