export const latestProjectsPropsPrimary = [
    {
        id: 1.1,
        title: "power organizer",
        alt: "power-organizer",
        imgSrc: "../../images/power-organizer.jpg",
        linkHref: "",
        technologies: ["React.js", "JavaScript", "Material UI"],
        description: "helps you keep track of your todos depending on the calendar",
    },
    {
        id: 1.2,
        title: "dizzy notes",
        alt: "dizzy-notes",
        imgSrc: "../../images/dizzy-notes.jpg",
        linkHref: "https://anaseiculescu.github.io/keep-notes/",
        technologies: ["JavaScript", "Masonry", "CSS", "Web Storage API"],
        description: "your can add and delete coloured notes, storaged locally / with node-storage api",
    },
    {
        id: 1.3,
        title: "call a cat with the CatAPI",
        alt: "call-a-cat",
        imgSrc: "../../images/catAPI.jpg",
        linkHref: "https://cat-caller.netlify.app/#",
        technologies: ["React.js", "The Cat API", "Bootstrap", "Netlify"],
        description: "call how many cat you want to colect, from The Cat API",
    },
    {
        id: 1.4,
        title: "collection map",
        alt: "collection-map",
        imgSrc: '"../../images/collection-map.jpg',
        linkHref: "https://anaseiculescu.github.io/collection-map/",
        technologies: ["JavaScript", "jQuery", "GoogleMapsAPI", "CSS"],
        description: "search for locations and you can collect them on your map and in your list",
    },
];

export const latestProjectsPropsSecondary = [
    {
        id: 1.5,
        title: "power organizer",
        alt: "power-organizer",
        imgSrc: "../../images/power-organizer.jpg",
        linkHref: "",
        technologies: ["React.js", "JavaScript", "Material UI"],
        description: "helps you keep track of your todos depending on the calendar",
    },
    {
        id: 1.6,
        title: "dizzy notes",
        alt: "dizzy-notes",
        imgSrc: "../../images/dizzy-notes.jpg",
        linkHref: "https://anaseiculescu.github.io/keep-notes/",
        technologies: ["JavaScript", "Masonry", "CSS", "Web Storage API"],
        description: "your can add and delete coloured notes, storaged locally / with node-storage api",
    },
    {
        id: 1.7,
        title: "call a cat with the CatAPI",
        alt: "call-a-cat",
        imgSrc: "../../images/catAPI.jpg",
        linkHref: "https://cat-caller.netlify.app/#",
        technologies: ["React.js", "The Cat API", "Bootstrap", "Netlify"],
        description: "call how many cat you want to colect, from The Cat API",
    },
    {
        id: 1.8,
        title: "collection map",
        alt: "collection-map",
        imgSrc: '"../../images/collection-map.jpg',
        linkHref: "https://anaseiculescu.github.io/collection-map/",
        technologies: ["JavaScript", "jQuery", "GoogleMapsAPI", "CSS"],
        description: "search for locations and you can collect them on your map and in your list",
    },
];

export const oldestProjectsPropsPrimary = [
    {
        id: 2.1,
        title: "color picker",
        alt: "color-picker",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["JavaScript", "CSS", "jQuery"],
        description: "",
    },
    {
        id: 2.2,
        title: "breakfast recipes",
        alt: "breakfast-recipes",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["CSS", "HTML", "Photoshop"],
        description: "",
    },
    {
        id: 2.3,
        title: "rock paper scissors lizard spock",
        alt: "rock-paper-scissors-lizard-spock",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["JavaScript", "CSS", "HTML"],
        description: "",
    },
    {
        id: 2.4,
        title: "my previous portfolio",
        alt: "previous-portfolio",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["JavaScript", "jQuery", "CSS"],
        description: "",
    },
];

export const oldestProjectsPropsSecondary = [
    {
        id: 2.5,
        title: "color picker",
        alt: "color-picker",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["JavaScript", "CSS", "jQuery"],
        description: "",
    },
    {
        id: 2.6,
        title: "breakfast recipes",
        alt: "breakfast-recipes",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["CSS", "HTML", "Photoshop"],
        description: "",
    },
    {
        id: 2.7,
        title: "rock paper scissors lizard spock",
        alt: "rock-paper-scissors-lizard-spock",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["JavaScript", "CSS", "HTML"],
        description: "",
    },
    {
        id: 2.8,
        title: "my previous portfolio",
        alt: "previous-portfolio",
        imgSrc: '"../../images/power-organizer.jpg',
        linkHref: "",
        technologies: ["JavaScript", "jQuery", "CSS"],
        description: "",
    },
];
